# Generated by Django 4.2.6 on 2023-10-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("greetings1", models.CharField(max_length=50)),
                ("greetings2", models.CharField(max_length=50)),
                ("picture", models.ImageField(upload_to="picture/")),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=200)),
                ("correo_electronico", models.CharField(max_length=255)),
                ("contrasena", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="gestionEmpleados.usuario",
                    ),
                ),
                (
                    "id_empleado",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                ("dni", models.CharField(max_length=30)),
                ("lugar_trabajo", models.CharField(max_length=200)),
            ],
            bases=("gestionEmpleados.usuario",),
        ),
        migrations.CreateModel(
            name="Gestores",
            fields=[
                (
                    "usuario_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="gestionEmpleados.usuario",
                    ),
                ),
                (
                    "id_gestor",
                    models.AutoField(default=0, primary_key=True, serialize=False),
                ),
                ("cargo", models.CharField(max_length=200)),
                ("oficina", models.CharField(max_length=100)),
            ],
            bases=("gestionEmpleados.usuario",),
        ),
        migrations.CreateModel(
            name="Salida",
            fields=[
                ("id_salida", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=200)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField(auto_now_add=True)),
                ("coordenadas", models.CharField(max_length=500)),
                ("direccion", models.CharField(max_length=1000)),
                ("link_mapa", models.CharField(max_length=1000)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salidas",
                        to="gestionEmpleados.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entrada",
            fields=[
                ("id_salida", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=200)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField(auto_now_add=True)),
                ("coordenadas", models.CharField(max_length=500)),
                ("direccion", models.CharField(max_length=1000)),
                ("link_mapa", models.CharField(max_length=1000)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas",
                        to="gestionEmpleados.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incidencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora", models.TimeField(auto_now_add=True)),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.CharField(max_length=10000)),
                ("lugar", models.CharField(max_length=100)),
                ("imagen", models.ImageField(upload_to="imagenes/")),
                ("documentos", models.FileField(upload_to="documentos/")),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionEmpleados.empleado",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asistencias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("entrada_hora", models.TimeField()),
                ("entrada_ubicacion", models.CharField(max_length=200)),
                ("salida_hora", models.TimeField()),
                ("salida_ubicacion", models.CharField(max_length=200)),
                ("area", models.CharField(blank=True, max_length=100, null=True)),
                ("updated", models.DateTimeField(auto_now_add=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionEmpleados.empleado",
                    ),
                ),
            ],
        ),
    ]
