# Generated by Django 4.2.6 on 2023-10-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestionEmpleados", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entrada",
            old_name="id_salida",
            new_name="id_entrada",
        ),
    ]
